
spring:
  profiles:
    include:
      - prod

### swagger
springdoc:
  swagger-ui:
    path: '/api-docs-ui'
    enabled: true
    docExpansion: 'none'
    # request, response media type
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
